[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0"
dashmap = "5.5.3"
tera = "1"
lazy_static = "1.4.0"
serde = { version = "1.0.197", features = ["derive"] }
chrono = "0.4.37"